environment:
  matrix:
    - MSVC_PLATFORM: x86
      PYTHON_ROOT: Python34
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

build_script:
  - set PYTHON=C:\%PYTHON_ROOT%\python.exe
  - .appveyor/msvc.bat

deploy: off
