jobs:
  - job: MSYS2
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        py2-i686:
          MSYSTEM: MINGW32
          MSYS2_ARCH: i686
          PYTHON: python2
        py2-x86_64:
          MSYSTEM: MINGW64
          MSYS2_ARCH: x86_64
          PYTHON: python2
        py3-i686:
          MSYSTEM: MINGW32
          MSYS2_ARCH: i686
          PYTHON: python3
        py3-x86_64:
          MSYSTEM: MINGW64
          MSYS2_ARCH: x86_64
          PYTHON: python3
    steps:
      - script: |
          choco install msys2 --params="/InstallDir:%CD:~0,2%\msys64 /NoUpdate /NoPath"
        displayName: Install MSYS2
      - script: |
          set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
          %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syuu
        displayName: Update MSYS2
      - script: |
          set PATH=C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
          %CD:~0,2%\msys64\usr\bin\bash -lc "bash -x .azure-pipelines/msys2.sh"
        displayName: Test
        env:
          CHERE_INVOKING: yes
          CODECOV_TOKEN: $(CODECOV_TOKEN)
          CODECOV_BRANCH: $(Build.SourceBranchName)

  - job: MSVC
    timeoutInMinutes: 60
    pool:
      vmImage: vs2017-win2016
    strategy:
      matrix:
        Python37-x64:
          python.version: '3.7'
          python.arch: 'x64'
        Python37-x86:
          python.version: '3.7'
          python.arch: 'x86'
        Python36-x64:
          python.version: '3.6'
          python.arch: 'x64'
        Python36-x86:
          python.version: '3.6'
          python.arch: 'x86'
        Python35-x64:
          python.version: '3.5'
          python.arch: 'x64'
        Python35-x86:
          python.version: '3.5'
          python.arch: 'x86'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: '$(python.arch)'
      - script: |
          choco install 7zip wget
        displayName: Install Dependencies
      - script: |
          call .azure-pipelines\msvc.bat
        displayName: Build & Test
        env:
          MSVC_PLATFORM: $(python.arch)
          CODECOV_TOKEN: $(CODECOV_TOKEN)
          CODECOV_BRANCH: $(Build.SourceBranchName)
          PYTHON: python
