[tool.poetry]
name = "pycairo"
version = "1.20.1"
description = "Python interface for cairo"
authors = ["Christoph Reiter"]

[tool.poetry.dependencies]
python = "^3.8.1"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
hypothesis = "^6.58.0"
mypy = {version = "^0.991", markers = "platform_python_implementation != 'PyPy'"}
flake8 = "^6.0.0"
Sphinx = "^6.2.1"
sphinx-rtd-theme = "^1.1.1"
coverage = "^7.2.3"
sphinx-autobuild = "^2021.3.14"
setuptools = "^67.8.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
