[tool.poetry]
name = "pycairo"
version = "1.26.2"
description = "Python interface for cairo"
authors = ["Christoph Reiter"]
packages = [
    { include = "cairo" },
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.2.0"
hypothesis = "^6.58.0"
mypy = {version = "1.8.0", markers = "platform_python_implementation != 'PyPy'"}
flake8 = "^7.0.0"
Sphinx = "^6.2.1"
sphinx-rtd-theme = "^2.0.0"
coverage = "^7.2.3"
sphinx-autobuild = "^2021.3.14"
setuptools = "^69.0.3"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
