[tool.poetry]
name = "pycairo"
version = "1.20.1"
description = "Python interface for cairo"
authors = ["Christoph Reiter"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^7.0.1"
hypothesis = "^6.0.0"
mypy = {version = "^0.931", markers = "platform_python_implementation != 'PyPy'"}
flake8 = "^3.9.2"
Sphinx = "^5.3.0"
sphinx-rtd-theme = "^1.0.0"
coverage = "^6.3.2"
sphinx-autobuild = "^2021.3.14"

[build-system]
requires = ["setuptools", "wheel"]
